name: taqaproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # ATT (iOS)
  app_tracking_transparency: ^2.0.4

  # UMP (GDPR consent)
  google_mobile_ads: ^5.0.0

  # Notifications (iOS + Android 13+)
  firebase_messaging: ^15.0.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_native_timezone: ^2.0.0



  # Location permission
  geolocator: ^12.0.0

  # Camera / Mic / Photos runtime permissions
  permission_handler: ^12.0.1

  # Core utilities
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.3.2
  image_picker: ^1.0.8
  file_picker: ^8.0.0

  # Social login
  flutter_signin_button: ^2.1.1
  google_sign_in: ^6.2.1
  health: ^13.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_gen:
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations
    output-dir: lib/generated/l10n
